[package]
name = "token-metadata-minocrab-benchmark"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
minocrab = { git = "https://github.com/sig-net/minocrab", rev = "99504f0df6633c2ef8720d060ccb9f141f6d06b7" }
minocrab-ledger = { git = "https://github.com/sig-net/minocrab", rev = "99504f0df6633c2ef8720d060ccb9f141f6d06b7" }
minocrab-sim = { git = "https://github.com/sig-net/minocrab", rev = "99504f0df6633c2ef8720d060ccb9f141f6d06b7", features = ["unstable"] }
minocrab-std = { git = "https://github.com/sig-net/minocrab", rev = "99504f0df6633c2ef8720d060ccb9f141f6d06b7" }
minocrab-zkir = { git = "https://github.com/sig-net/minocrab", rev = "99504f0df6633c2ef8720d060ccb9f141f6d06b7" }

[dev-dependencies]
midnight-base-crypto = { git = "https://github.com/midnightntwrk/midnight-ledger", rev = "04c9c5d9bcebb8d4427d8589fb54d58a55599c14" }
midnight-onchain-state = { git = "https://github.com/midnightntwrk/midnight-ledger", rev = "04c9c5d9bcebb8d4427d8589fb54d58a55599c14" }
midnight-onchain-vm = { git = "https://github.com/midnightntwrk/midnight-ledger", rev = "04c9c5d9bcebb8d4427d8589fb54d58a55599c14" }
midnight-storage = { git = "https://github.com/midnightntwrk/midnight-ledger", rev = "04c9c5d9bcebb8d4427d8589fb54d58a55599c14" }
midnight-transient-crypto = { git = "https://github.com/midnightntwrk/midnight-ledger", rev = "04c9c5d9bcebb8d4427d8589fb54d58a55599c14" }

[patch.crates-io]
midnight-transient-crypto = { git = "https://github.com/midnightntwrk/midnight-ledger", tag = "transient-crypto-2.2.0-rc.1" }
midnight-serialize = { git = "https://github.com/midnightntwrk/midnight-ledger", rev = "04c9c5d9bcebb8d4427d8589fb54d58a55599c14" }
midnight-base-crypto = { git = "https://github.com/midnightntwrk/midnight-ledger", rev = "04c9c5d9bcebb8d4427d8589fb54d58a55599c14" }

[profile.dev]
debug = 0
split-debuginfo = "off"

[profile.test]
debug = 0
split-debuginfo = "off"

[profile.release]
debug = 0
strip = "debuginfo"
